name: Devops-Blanc

on:
  pull_request:
  push:
      branches:
        - features-*
        # - features

permissions:
  contents: write
  pull-requests: write

jobs:

  #   ##############################################################
  #   # JOB 1 - Build l'env python et effectuer les tests unitaires #
  #   ##############################################################

  build_and_test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/features-')
    steps:

    ################################
    # Checkout #
    ################################
    - name: Checkout - Récuparation du projet
      uses: actions/checkout@v4


    ################################
    # Python #
    ################################

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    ################################
    # Tests   #
    ################################

    - name: Rendre les fichiers sh exécutable
      run: chmod u+x scripts/*

    - name: Génération de la doc main.md
      run: scripts/mkdoc.sh

    - name: Tests unitaires
      run: scripts/mktest.sh

  #   ##################################################################
  #   # Job 2 Créer une pull request pour la branche principale features #
  #   ##################################################################

  pull_request_features :
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:

    # recupération du repository
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: Création de la pull request
      id: open-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: 'Envoi vers features - Commit numéro: ${{github.sha}}'
        title: 'Envoi vers features - Commit numéro: ${{github.sha}}'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: feature, automated pr
        branch: features
      
  #   ###########################################################
  #   # Job 3 Merger la branche de feature dans la branche main #
  #   ###########################################################

  merge_on_stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:

    # recupération du repository
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: Création de la pull request
      id: open-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: 'Envoi vers stage - Commit numéro: ${{github.sha}}'
        title: 'Envoi vers stage - Commit numéro: ${{github.sha}}'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: feature, automated pr
        branch: stage
        # delete-branch: false
        author: ${{ github.actor }}
        # assignees: ${{ github.actor }}
        # reviewers: Bahamut0

      # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: Activer la merge automatique
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: squash


  #   ###########################################################
  #   # Job 4 Merger la branche de stage dans la branche main #
  #   ###########################################################

  merge_on_main:
    needs: merge_on_stage
    runs-on: ubuntu-latest
    steps:

    # recupération du repository
    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # https://github.com/marketplace/actions/github-pull-request-action
    - name: Création de la pull request
      id: open-pr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: 'Envoi vers main - Commit numéro: ${{github.shar}}'
        title: 'Envoi vers main - Commit numéro: ${{github.sha}}'
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        labels: feature, automated pr
        branch: main
        author: ${{ github.actor }}

      # https://github.com/marketplace/actions/enable-pull-request-automerge
    - name: Activer la merge automatique
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: squash
        

      
  

      