name: Devops-Blanc

on:

  push:
      branches:
        - features-*
        - main

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/test'
    if: startsWith(github.ref, 'refs/heads/features-')
    steps:

    ################################
    # Checkout #
    ################################
    - name: Checkout - Récuparation du projet
      uses: actions/checkout@v4


    ################################
    # Python #
    ################################

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    ################################
    # Tests   #
    ################################

    - name: Rendre les fichiers sh exécutable
      run: chmod u+x scripts/*

    - name: Génération de la doc main.md
      run: scripts/mkdoc.sh

    - name: Tests unitaires
      run: scripts/mktest.sh
      
  merge_on_main:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:

  #   ################################
  #   # Checkout #
  #   ################################

    - name: git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #   ################################
  #   # Create PR #
  #   ################################



  #   ################################
  #   # Merge #
  #   ################################
  #   - name: Checkout - Récuparation du projet
  #     uses: actions/checkout@v4

      
  

      