name: Devops-Blanc

on:

  push:
    branches: [ feature-*, main ]
    
  pull_request:
    branches: [ feature-*, features, stage, main ]
    types: [opened, closed]

  release:
    types: [published]
    
              

permissions:
  contents: write
  pull-requests: write


jobs:

  #   ##################################################################
  #   # Job 1 Créer une pull request pour la branche principale features #
  #   ##################################################################

  createPullRequest:
    runs-on: ubuntu-latest

    # Condition 1: Ecouter uniquement les push sur les branches ayant pour motif "feature-XXX"
    # Condition 2: Ne pas écouter les push qui sont créé via des merges de pull request (évite les pull request infinies)
    if: (contains(github.ref, 'feature-') && github.event_name == 'push' && contains(toJSON(github.event.head_commit.message), 'Merge pull request') == false)
 
    steps:
      - uses: actions/checkout@v4

      - name: create pull request
        run: gh pr create -B features -H ${{github.ref}} --title 'Merge ${{github.ref}} into features' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ##############################################################
    # JOB 2 - Build l'env python et effectuer les tests unitaires #
    ##############################################################

  build_and_test:

    # Ne fonctionne que si la branche features a été mergée après une pull request validée
    if: github.event.pull_request.merged

    runs-on: ubuntu-latest

    steps:

    ################################
    # Checkout #
    ################################
    - name: Checkout - Récuparation du projet
      uses: actions/checkout@v4

    - name: Récupération de la branche courante (base)
      run: echo ${{ github.ref }} 

    ################################
    # Python #
    ################################

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    ################################
    # Tests   #
    ################################

    - name: Rendre les fichiers sh exécutable
      run: chmod u+x scripts/*

    - name: Génération de la doc main.md
      run: scripts/mkdoc.sh

    - name: Tests unitaires
      run: scripts/mktest.sh


  # #   ###########################################################
  # #   # JOB 3 Merger la branche de feature dans la branche main #
  # #   ###########################################################

  merge_on_stage:

    needs: build_and_test
    runs-on: ubuntu-latest
    
    steps:
        
    # recupération du repository
    - name: git checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        fetch-depth: 0
        # ref: stage


    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: stage
        base: features


  #   ###########################################################
  #   # Job 4 Merger la branche de stage dans la branche main #
  #   ###########################################################

  merge_on_main:
    needs: merge_on_stage
    runs-on: ubuntu-latest
    steps:

    # recupération du repository
    - name: git checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create Pull Request
      id: prm
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        branch: main
        base: stage
  
  release:
    needs: merge_on_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # fetch-depth: 0


      # - name: Changement de version et tag
        # id: tag_version
        # uses: mathieudutour/github-tag-action@v6.2
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   # default_bump: minor
        #   # en cas de commit_sha: false error : At least 40 characters are required; only 5 were supplied
        #   # commit_sha: false
        # uses: juliansangillo/tag-version@v1  
        # with:  
        #     production-branch: main 
        #     test-branch: stage  
        #     dev-branch: features  

          # - name: Création d'une release GitHub
      #   uses: ncipollo/release-action@v1
      #   with:
          
      #     # tag: ${{ steps.tag_version.outputs.new_tag }}
      #     # name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     # body: ${{ steps.tag_version.outputs.changelog }}
      #     tag: ${{ steps.tag_version.outputs.revision }}
      #     name: ${{ steps.tag_version.outputs.revision }}
      #     # body: ${{ steps.tag_version.outputs.description }} 

      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.version }}

      - name: Création d'une release GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.package-version.outputs.version }}
          name: v${{ steps.package-version.outputs.version }}
          body: ${{ steps.package-version.outputs.changelog }}

          
          
   
  

      